name: commandannouncer
version: '${version}'
main: me.loloed.commandannouncer.CommandAnnouncer
api-version: '1.20'
authors: [loloed]
commands:
  announcerworking:
    description: is the logger working