name: commandannouncer
version: '${version}'
main: me.loloed.commandannouncer.CommandAnnouncer
api-version: '1.20'
authors: [loloed]
commands:
  announcerworking:
    permission: announcer

permissions:
  announcer:
    default: true